---
title: "Buoy_data_vis"
author: "Wendel Raymond"
date: "November 2, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# NOAA buoy data visulaization
Data summaries and visualizations of NOAA buoy data

libraries
```{r lib}
library(data.table)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(clifro)
library(scales)

theme_set(theme_classic())
```

## Data

46087 - Cape Flattery
46267 - Angeles Point
```{r data}
## Get raw data  ##
cflat <- fread("https://www.ndbc.noaa.gov/data/5day2/46087_5day.txt")
cflat <- cflat[2:nrow(cflat),]
colnames(cflat)[1] <- "YY"

## Concatenate time ##
cflat <- cflat %>% mutate_if(is.character, as.numeric)

time.stamp <- cflat %>% 
  select(YY, MM, DD, hh, mm) %>% 
  mutate(time = make_datetime(YY, MM, DD, hh, mm))

cflat <- cbind(cflat, time.stamp$time)
colnames(cflat)[20] <- "time"

### Define time ###
cflat$time <- as.POSIXct(cflat$time,  format = "%y%m%d %H:%M:%S", tz = "UTC")

### Convert time ###
cflat$time <- with_tz(cflat$time, tzone = Sys.timezone())

## Remove NA ##
cflat <- cflat[!is.na(cflat$WVHT), ]
cflat <- cflat[!is.na(cflat$DPD), ]

## Trim data to last 48 hours ##
cflat <- cflat %>% 
  filter(time) 
```

## Plots
```{r}
ggplot(cflat) +
  geom_line(aes(x = time, y = WVHT), size = 1) +
  scale_x_datetime(labels = date_format("%m%d %H:%M"), date_breaks = "6 hour", date_labels = "%d-%m-%Y") +
  scale_y_continuous(limits = c(0, max(cflat$WVHT)), breaks = seq(0, max(cflat$WVHT))) +
  ylab("Wave height (ft)") +
  xlab("Time")

ggplot(cflat) +
  geom_line(aes(x = time, y = MWD), size = 1) +
  scale_y_continuous(limits = c(0, 360), breaks = seq(0, 360, by = 30)) +
  geom_hline(aes(yintercept = 0)) +
  geom_hline(aes(yintercept = 90)) +
  geom_hline(aes(yintercept = 180)) +
  geom_hline(aes(yintercept = 270)) +
  geom_hline(aes(yintercept = 360)) +
  geom_hline(aes(yintercept = 315), color = "red") +
  ylab("Mean wave direction (degrees)") +
  xlab("Time")

ggplot(cflat) +
  geom_line(aes(x = time, y = DPD), color = "black", size = 1) +
  geom_line(aes(x = time, y = APD), color = "blue", size = 1) +
  scale_y_continuous(limits = c(0, max(cflat$DPD)), breaks = seq(0, max(cflat$DPD))) +
  ylab("Wave period (sec)") +
  xlab("Time")
```

